### ISSUE TITLE
Blank Kippo Playlog page

### ISSUE THREAD

**Issue by yaglol** [ikoniaris/kippo-graph#61]
https://imgur.com/a/ZCq4R

My kippo Playlog-page is currently blank, i know there is data in the MySQL tables and every other statistics page works like a charm, any ideas?

**Comment by biggen1684** [comment]
Did you get this sorted out?  I'm also having problems with playback and I'm missing graphs.

**Comment by yaglol** [comment]
I have not found any fix to this yet :/ @biggen1684 

EDIT: but i am not missing any graphs tho

**Comment by biggen1684** [comment]
Im not sure why Im missing half my graphs. I started a new issue for that. I get php errors in the apache log.  Wierd

**Comment by ikoniaris** [comment]
Can you both post any sort of logs/errors/something you can get from Apache? :)

**Comment by overcore456** [comment]
Hi everyone,
I experience the same issue with blank pages (Graph, Payload, Geo). I freshly deployed an AWS Ubuntu 16.04. I couldn't install the mentioned packages (php5) on this Ubuntu release, so I used libapache2-mod-php, php-mysql,php-gd, php-curl instead. I guess all packages are now related to PHP7 in this case and this might case the issue because if I use an older release with a PHP5 environment I do not run into any issues.

PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15-0ubuntu0.16.04.4, Copyright (c) 1999-2017, by Zend Technologies


I checked my apache2 error log while accessing those pages:

[Mon May 01 06:55:58.775602 2017] [:error] [pid 4553] [client x.x.x.x:56666] PHP Fatal error:  Uncaught [42000] - SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'cowrie.auth.timestamp' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by\ntrace: #0 /var/www/html/include/rb.php(785): RedBeanPHP\\Driver\\RPDO->runQuery('SELECT COUNT(se...', Array)\n#1 /var/www/html/include/rb.php(3035): RedBeanPHP\\Driver\\RPDO->GetAll('SELECT COUNT(se...', Array)\n#2 /var/www/html/include/rb.php(9305): RedBeanPHP\\Adapter\\DBAdapter->get('SELECT COUNT(se...', Array)\n#3 /var/www/html/include/rb.php(9936): RedBeanPHP\\Facade::query('get', 'SELECT COUNT(se...', Array)\n#4 /var/www/html/class/KippoGraph.class.php(253): RedBeanPHP\\Facade::getAll('SELECT COUNT(se...')\n#5 /var/www/html/class/KippoGraph.class.php(26): KippoGraph->createMostSuccessfulLoginsPerDay()\n#6 /var/www/html/kippo-graph.php(62): KippoGraph->generateKippoGraphCharts()\n#7 {main}\n  thrown in /var/www/html/include/rb.php on line 636, referer: http://x.x.x.x/kippo-geo.php


[Mon May 01 06:56:55.089702 2017] [:error] [pid 4321] [client x.x.x.x:1033] PHP Fatal error:  Uncaught [42000] - SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'cowrie.input.timestamp' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by\ntrace: #0 /var/www/html/include/rb.php(785): RedBeanPHP\\Driver\\RPDO->runQuery('SELECT COUNT(in...', Array)\n#1 /var/www/html/include/rb.php(3035): RedBeanPHP\\Driver\\RPDO->GetAll('SELECT COUNT(in...', Array)\n#2 /var/www/html/include/rb.php(9305): RedBeanPHP\\Adapter\\DBAdapter->get('SELECT COUNT(in...', Array)\n#3 /var/www/html/include/rb.php(9936): RedBeanPHP\\Facade::query('get', 'SELECT COUNT(in...', Array)\n#4 /var/www/html/class/KippoInput.class.php(94): RedBeanPHP\\Facade::getAll('SELECT COUNT(in...')\n#5 /var/www/html/kippo-input.php(64): KippoInput->printHumanActivityBusiestDays()\n#6 {main}\n  thrown in /var/www/html/include/rb.php on line 636, referer: http://x.x.x.x/kippo-input.php


[Mon May 01 06:57:35.706101 2017] [:error] [pid 4318] [client x.x.x.x:58451] PHP Fatal error:  Uncaught [42000] - SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'cowrie.auth.timestamp' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by\ntrace: #0 /var/www/html/include/rb.php(785): RedBeanPHP\\Driver\\RPDO->runQuery('SELECT * FROM (...', Array)\n#1 /var/www/html/include/rb.php(3035): RedBeanPHP\\Driver\\RPDO->GetAll('SELECT * FROM (...', Array)\n#2 /var/www/html/include/rb.php(9305): RedBeanPHP\\Adapter\\DBAdapter->get('SELECT * FROM (...', Array)\n#3 /var/www/html/include/rb.php(9936): RedBeanPHP\\Facade::query('get', 'SELECT * FROM (...', Array)\n#4 /var/www/html/class/KippoPlayLog.class.php(30): RedBeanPHP\\Facade::getAll('SELECT * FROM (...')\n#5 /var/www/html/kippo-playlog.php(62): KippoPlayLog->printLogs()\n#6 {main}\n  thrown in /var/www/html/include/rb.php on line 636, referer: http://x.x.x.x/kippo-input.php


[Mon May 01 06:58:05.981668 2017] [:error] [pid 4331] [client x.x.x.x:40016] PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/include/qgooglevisualapi/QVizualisationGoogleGraph.class.php:123\nStack trace:\n#0 /var/www/html/class/KippoGeo.class.php(93): QVizualisationGoogleGraph->__construct()\n#1 /var/www/html/kippo-geo.php(61): KippoGeo->printKippoGeoData()\n#2 {main}\n  thrown in /var/www/html/include/qgooglevisualapi/QVizualisationGoogleGraph.class.php on line 123, referer: http://x.x.x.x/kippo-geo.php

Any suggestions? :-)

Cheers

**Comment by overcore456** [comment]
I was able to fix all issues: 

- the SimpleXMLElement error by running "sudo apt-get install php7.0-xml"
- disabling MySQL strict mode by creating a new file /etc/mysql/conf.d/disable_strict_mode.cnf with the following content:
[mysqld]
sql_mode=IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

After restarting the apache and MySQL service, everything is back to normal. :-)
