### ISSUE TITLE
Oveview, Input, and Playlog doesnt work well.

### ISSUE THREAD

**Issue by havesalghofiqi** [ikoniaris/kippo-graph#73]
here my screenshoot.

![image](https://user-images.githubusercontent.com/36653654/46033969-b50abd80-c129-11e8-8756-5fdf0d453980.png)

![image](https://user-images.githubusercontent.com/36653654/46033913-91e00e00-c129-11e8-9697-0a51c4f4d58b.png)

![image](https://user-images.githubusercontent.com/36653654/46033951-a7edce80-c129-11e8-993b-2ddeedef4ede.png)

and here is some of my Apache2 error log 

`
[Wed Sep 26 01:10:01.959728 2018] [:error] [pid 5208] [client 202.43.95.33:21040] PHP Fatal error:  Uncaught [42000] - SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'kippo.auth.timestamp' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by\ntrace: #0 /var/www/html/kippo-graph/include/rb.php(785): RedBeanPHP\\Driver\\RPDO->runQuery('SELECT COUNT(se...', Array)\n#1 /var/www/html/kippo-graph/include/rb.php(3035): RedBeanPHP\\Driver\\RPDO->GetAll('SELECT COUNT(se...', Array)\n#2 /var/www/html/kippo-graph/include/rb.php(9305): RedBeanPHP\\Adapter\\DBAdapter->get('SELECT COUNT(se...', Array)\n#3 /var/www/html/kippo-graph/include/rb.php(9936): RedBeanPHP\\Facade::query('get', 'SELECT COUNT(se...', Array)\n#4 /var/www/html/kippo-graph/class/KippoGraph.class.php(293): RedBeanPHP\\Facade::getAll('SELECT COUNT(se...')\n#5 /var/www/html/kippo-graph/class/KippoGraph.class.php(27): KippoGraph->createMostSuccessfulLoginsPerDay()\n#6 /var/www/html/kippo-graph/kippo-graph.p in /var/www/html/kippo-graph/include/rb.php on line 636, referer: http://206.189.84.56/kippo-graph/kippo-graph.php
[Wed Sep 26 01:10:03.387744 2018] [:error] [pid 5217] [client 202.43.95.33:21041] PHP Fatal error:  Uncaught [42000] - SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'kippo.input.timestamp' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by\ntrace: #0 /var/www/html/kippo-graph/include/rb.php(785): RedBeanPHP\\Driver\\RPDO->runQuery('SELECT COUNT(in...', Array)\n#1 /var/www/html/kippo-graph/include/rb.php(3035): RedBeanPHP\\Driver\\RPDO->GetAll('SELECT COUNT(in...', Array)\n#2 /var/www/html/kippo-graph/include/rb.php(9305): RedBeanPHP\\Adapter\\DBAdapter->get('SELECT COUNT(in...', Array)\n#3 /var/www/html/kippo-graph/include/rb.php(9936): RedBeanPHP\\Facade::query('get', 'SELECT COUNT(in...', Array)\n#4 /var/www/html/kippo-graph/class/KippoInput.class.php(98): RedBeanPHP\\Facade::getAll('SELECT COUNT(in...')\n#5 /var/www/html/kippo-graph/kippo-input.php(39): KippoInput->printHumanActivityBusiestDays()\n#6 {main}\n  thrown in /var/www/html/kippo-graph/include/rb.php on line 636, referer: http://206.189.84.56/kippo-graph/kippo-graph.php
[Wed Sep 26 01:10:04.930368 2018] [:error] [pid 5825] [client 202.43.95.33:21042] PHP Fatal error:  Uncaught [42000] - SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'kippo.auth.timestamp' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by\ntrace: #0 /var/www/html/kippo-graph/include/rb.php(785): RedBeanPHP\\Driver\\RPDO->runQuery('SELECT COUNT(se...', Array)\n#1 /var/www/html/kippo-graph/include/rb.php(3035): RedBeanPHP\\Driver\\RPDO->GetAll('SELECT COUNT(se...', Array)\n#2 /var/www/html/kippo-graph/include/rb.php(9305): RedBeanPHP\\Adapter\\DBAdapter->get('SELECT COUNT(se...', Array)\n#3 /var/www/html/kippo-graph/include/rb.php(9936): RedBeanPHP\\Facade::query('get', 'SELECT COUNT(se...', Array)\n#4 /var/www/html/kippo-graph/class/KippoGraph.class.php(293): RedBeanPHP\\Facade::getAll('SELECT COUNT(se...')\n#5 /var/www/html/kippo-graph/class/KippoGraph.class.php(27): KippoGraph->createMostSuccessfulLoginsPerDay()\n#6 /var/www/html/kippo-graph/kippo-graph.p in /var/www/html/kippo-graph/include/rb.php on line 636, referer: http://206.189.84.56/kippo-graph/kippo-input.php
`

**Comment by havesalghofiqi** [comment]
SOLVED https://github.com/ikoniaris/kippo-graph/issues/61#issuecomment-298472414
